spring.datasource.url=${DB_URL:postgresql://postgres:WmcoQAmTPMUdxzjhieXjopXnwMuIuSeg@metro.proxy.rlwy.net:49237/railway}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:WmcoQAmTPMUdxzjhieXjopXnwMuIuSeg}


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}